const fs = require('fs');
const inquirer = require('inquirer');
const axios = require('axios');
const puppeteer = require('puppeteer');

// Inquirer gathering Github username
function promptUser() {
    return inquirer.prompt([
        {
            type: "input",
            name: "gitPro",
            message: "What is your GitHub account?"
        },
        {
            type: "input",
            name: "color",
            message: "What is your favorite color? (Any non-white color)"
        }
    ]);
}

//Template literal of html based on User input
function generateHTML(data, answers) {
    return `<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        <link rel="stylesheet" href="./assets/style.css">
    </head>
    <body style="background-color:${answers.color};">
        <h1>${data.login}</h1>
        <img src="${data.avatar_url}">
        <h3>Location: ${data.location}</h3>
        <h3 id="bio">${data.bio}</h3>
        <h2>GitHub Stats!</h2>
        <h2><a href="${data.html_url}">${data.html_url}</a></h2>
        <div>
            <p>Followers: ${data.followers}</p>
            <p>Following: ${data.following}</p>
            <p>Public Repos: ${data.public_repos}</p>
        </div>
    </body>
    </html>`
}

async function init() {
    try {
        //Call to Github API + variables generated by PromptUser();
        const answers = await promptUser();
        if (answers.color == "white") {
            answers.color = "lightblue";
        }

        const { data } = await axios.get(`https://api.github.com/users/${answers.gitPro}`)
        const html = generateHTML(data, answers);
        
        //Writes template literal to index.html file
        fs.writeFile("index.html", html, (err) => {
            if (err) throw err;
            console.log("Wrote to index.html!");
        });

        //Puppeteer function that throws html onto browser, takes a pic,
        //then turns it into a .pdf file.
        (async () => {
            const browser = await puppeteer.launch();
            const page = await browser.newPage();

            await page.goto("file://C:/Users/dusti/desktop/dynamicPort/index.html");
            await page.pdf({ path: 'portfolio.pdf', format: 'A4', printBackground: true});
            await browser.close();
            console.log("Portfolio made! Thank you for using our app!");
        })();

    } catch (err) {
        console.log(err);
    }

}

init();
